# Generated by Django 5.2 on 2025-04-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('skill', models.TextField()),
                ('line', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
