# Generated by Django 5.2 on 2025-04-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_myskills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myskills',
        ),
    ]
