# Generated by Django 5.2 on 2025-04-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_myprojects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_info',
        ),
    ]
